package it.fitnesschallenge.model;

public final class SharedConstance {
    public static final String HOME_FRAGMENT = "homeFragment";
    public static final String LOGIN_FRAGMENT = "loginFragment";
    public static final String PROFILE_FRAGMENT = "ProfileFragment";
    public static final String TIMER_FRAGMENT = "timerFragment";
    public static final String SETTING_FRAGMENT = "settingFragment";
    public static final String LAST_FRAGMENT = "lastFragment";
    public static final String SIGN_UP_FRAGMENT = "signInFragment";
    public static final String TRAINER_HOME_FRAGMENT = "trainerHomeFragment";
    public static final String SHARED_PREFERENCES = "sharedPreferences";
    public static final String LOGGED_IN = "loggedIn";
    public static final String AUTO_LOGGED = "autoLogin";
    public static final String USE_NFC = "useNFC";
    public static final String CREATE_TRAINING_LIST = "createTrainingList";
    public static final String ADD_USERNAME_AND_START_DATE = "addUsernameAndStartDate";
    public static final String ADD_EXERCISE_TO_WORKOUT = "addExerciseToWorkout";
    public static final String ADD_FINISH_DATE = "addFinishDate";
    public static final String UPLOAD_NEW_WORKOUT = "uploadNewWorkout";
    public static final String EXERCISE_LIST = "exerciseList";
    public static final String DATE_PICKER = "datePicker";
    public static final String SELECTED_DATE = "selectedDate";
    public static final String WORKOUT_FRAGMENT = "workoutFragment";
    public static final String ADD_EXERCISE_TO_LIST = "addExerciseToList";
    public static final String WORKOUT_STATISTICS_FRAGMENT = "workoutStatisticsFragment";
    public static final String ENTER_FRAGMENT = "enterFragment";
    public static final String GYM_HOME_FRAGMENT = "gymHomeFragment";
    public static final String PLAYING_WORKOUT = "playingWorkout";
    public static final String SELECTED_TIMER = "selectedTimer";
    public static final String POSITION_IN_ADAPTER = "positionInAdapter";
    public static final String TIME_FOR_TIMER = "timeForTimer";
    public final static int CONVERSION_SEC_IN_MILLIS = 1000;
    public final static String ADD_WEIGHT = "addWeight";
    public final static String UPLOAD_WORKOUT_ON_FIREBASE = "uploadWorkoutOnFirebase";
    public final static String ROOM_FRAGMENT = "roomFragment";
    public final static String WORKOUT_LIST_FRAGMENT = "workoutListFragment";
    public final static String EDIT_LIST_FRAGMENT = "editListFragment";
    public final static String USER_DETAIL_FRAGMENT = "userDetailFragment";
}
